# Используем официальный образ .NET SDK для сборки
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Устанавливаем рабочую директорию
WORKDIR /src

# Копируем все файлы проекта
COPY . .

# Восстанавливаем зависимости и публикуем приложение
RUN dotnet restore
RUN dotnet publish -c Release -o /app

# Используем официальный образ .NET Runtime для запуска
FROM mcr.microsoft.com/dotnet/aspnet:6.0

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем собранное приложение из предыдущего этапа
COPY --from=build /app .

# Указываем точку входа
ENTRYPOINT ["dotnet", "Standoff2BoostBot.dll"]